##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [1]:
import numpy as np
arr = np.array([10,20,30,40,50,60])

arr [[1,3]]


array([20, 40])

You can do this fancy indexing in 2D Matrix aswell

In [3]:
matrix = np.arange(1,13).reshape(3,4)
matrix
matrix[[0,2],[1,2]]

array([ 2, 11])

##Conditional Selection
Find values based on conditions or replace them.

In [8]:
arr =np.array([1,2,3,4,5,11,17])

np.where(arr > 10,arr,0)


array([ 0,  0,  0,  0,  0, 11, 17])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [10]:
arr =np.array([22,43,54,34])
np.sort(arr)

array([22, 34, 43, 54])

In [11]:
arr =np.array([22,43,54,34])
np.argsort(arr)

array([0, 3, 1, 2])

##Concatenation & Stacking

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concat([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [14]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,12,13],[14,15,16]])

np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [17]:
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [18]:
np.concat([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])