##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a+b)
print(a-b)
print(a*b)
print(a//b)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0 0 0 0]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
a = np.array([1,2,3,4])
print(a*5)

[ 5 10 15 20]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
a = np.array([[1,2,3],[14,5,7]])
print(a*3)

[[ 3  6  9]
 [42 15 21]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [5]:
import numpy as np

arr = np.array([1,2,3,4])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

10
2.5
1
4
1.118033988749895
1.25


You can also do the axis based operations row-Wise and Colum-wise

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(np.sum(arr,axis = 1))
print(np.sum(arr,axis = 0))

[ 6 15 24]
[12 15 18]
