##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])


print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
a = np.array([1,2,3,4,5])
print(a[2])
print(a[-1])

3
5


Now lets see the 2D indexing aswell

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]

array([1, 2, 3])

In [ ]:
arr[0,2]

np.int64(3)

Now we can also do the slicing lets see the **slicing in 1D**

In [ ]:
a = np.array([1,2,3])
print(a[2])

3


1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([1,2,44,35,23])
print(arr > 20)
print(arr[arr > 20])

[False False  True  True  True]
[44 35 23]


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[arr > 6])


[7 8 9]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [3]:
np.arange(1,31).reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [5]:
a=np.arange(1,31).reshape(6,5)
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])